#!/bin/bash

iptables --flush
iptables -t nat --flush
iptables --delete-chain
iptables -t nat --delete-chain

echo "berhasil !!!"

read tomb;

if [ "$tomb" == "y" ]; then
   iptables -t nat -A PREROUTING -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.12.1:80
   iptables -t nat -A PREROUTING -p udp -m udp --dport 80 -j DNAT --to-destination 192.168.12.1:80
   iptables -t nat -A PREROUTING -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.12.1:80
   iptables -t nat -A PREROUTING -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.12.1:80
   
fi
